apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: grafana-https
  labels:
    app.kubernetes.io/name: grafana-gmp
spec:
  parentRefs:
    - name: {{ .Values.gateway.name }}
      namespace: {{ .Values.gateway.namespace }}
      sectionName: https
  {{- if .Values.gateway.hostname }}
  hostnames:
    - {{ .Values.gateway.hostname | quote }}
  {{- end }}
  rules:
    - backendRefs:
        - name: grafana
          port: 3000
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: grafana-http-redirect
  labels:
    app.kubernetes.io/name: grafana-gmp
spec:
  parentRefs:
    - name: {{ .Values.gateway.name }}
      namespace: {{ .Values.gateway.namespace }}
      sectionName: http
  {{- if .Values.gateway.hostname }}
  hostnames:
    - {{ .Values.gateway.hostname | quote }}
  {{- end }}
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
---
apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: grafana
  labels:
    app.kubernetes.io/name: grafana-gmp
spec:
  default:
    checkIntervalSec: 15
    timeoutSec: 5
    healthyThreshold: 2
    unhealthyThreshold: 3
    config:
      type: HTTP
      httpHealthCheck:
        portSpecification: USE_FIXED_PORT
        port: 3000
        requestPath: /api/health
  targetRef:
    group: ""
    kind: Service
    name: grafana
