{{- if and .Values.gateway.enabled .Values.healthCheckPolicy.enabled }}
apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: {{ include "moodle.fullname" . }}
  labels:
    {{- include "moodle.labels" . | nindent 4 }}
spec:
  default:
    checkIntervalSec: {{ .Values.healthCheckPolicy.checkIntervalSec }}
    timeoutSec: {{ .Values.healthCheckPolicy.timeoutSec }}
    healthyThreshold: {{ .Values.healthCheckPolicy.healthyThreshold }}
    unhealthyThreshold: {{ .Values.healthCheckPolicy.unhealthyThreshold }}
    config:
      type: HTTP
      httpHealthCheck:
        portSpecification: USE_FIXED_PORT
        port: {{ .Values.service.port }}
        requestPath: {{ .Values.healthCheckPolicy.requestPath | quote }}
  targetRef:
    group: ""
    kind: Service
    name: {{ include "moodle.fullname" . }}
{{- end }}
